Add missing cstring header
Fixes the following build errors:
  ../../flutter/shell/platform/linux/fl_key_event.cc:16:19:
  error: use of undeclared identifier 'strlen'
  size_t length = strlen(source);
                  ^
  ../../flutter/shell/platform/linux/fl_key_event.cc:18:3:
  error: use of undeclared identifier 'strncpy'
  strncpy(result, source, length + 1);
  ^
  2 errors generated.